server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "ultimateroleplay"
    sources:
      youtube: true
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false
